#!/bin/sh

ENABLED=yes

DESC="UPnP Media Server"
PROCS="gerbera"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/etc/$PROCS" ] || mkdir -pm 0750 /opt/etc/"$PROCS"
  [ -f "/opt/etc/$PROCS/config.xml" ] || \
  $PROG --create-config > /opt/etc/"$PROCS"/config.xml
}

PRECMD="start_pre"
ARGS="\
-f /opt/etc/$PROCS \
-m /opt/etc/$PROCS \
-l /opt/var/log/$PROCS.log \
-P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
