#!/bin/sh

ENABLED=yes

DESC="BIRD Internet Routing Daemon (IPv4)"
PROCS="bird4"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="-c /opt/etc/$PROCS.conf -P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
