#!/bin/sh

ENABLED=yes

DESC="DansGuardian"
PROCS="dansguardian"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
  [ -d "/opt/var/log/$PROCS" ] || \
  mkdir -pm /opt/var/log/"$PROCS"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
