#!/bin/sh

ENABLED=yes

DESC="Open Direct Connect hub"
PROCS="opendchub"
PROG="/opt/bin/$PROCS"

#export ODCH_HOME="/opt/var/lib/$PROCS"

start_pre() {
  [ -d "/opt/var/lib/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/lib/"$PROCS"
  cat /opt/etc/$PROCS.conf > /opt/var/lib/"$PROCS"/config
}

PRECMD="start_pre"
ARGS="-w /opt/var/lib/$PROCS"
PREARGS=""

. /opt/etc/init.d/rc.func
