#!/bin/sh

ENABLED=yes

DESC="ProFTPD server"
PROCS="proftpd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"

start_pre() {
  [ -d "/opt/var/run/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/run/"$PROCS"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
